name: Terraform Workflow

on:
  push:
    branches:
      - main  # Endre til din standardgren hvis nødvendig
  pull_request:
    branches:
      - main  # Trigger for pull requests til main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Endre til ønsket versjon av Terraform

      - name: Terraform Init
        run: terraform init
        working-directory: /cloudwatch_alarms_terraform/infra

      - name: Terraform Plan
        run: terraform plan
        working-directory: /cloudwatch_alarms_terraform/infra

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: /cloudwatch_alarms_terraform/infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Legg til AWS Secrets i GitHub
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
